name: multi_select_search
description: Easily buildable and customizable multi select widget with search field that can be used anywhere from container to dialog
version: 0.0.2
homepage: https://github.com/Loverofart/multi_select_search

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
